### ISSUE TITLE
Percentage-based rollout strategy not working

### ISSUE THREAD

**Issue by tank-pooja** [featurehub-io/featurehub-go-sdk#11]
@chrusty , I am following the example given for the custom rollout strategies feature and percentage-based rollout strategy, but none of them is working. In the SDK capabilities table, it is mentioned that Rollout Strategies - Server Evaluated* and Rollout Strategies - Client Evaluated*, are not supported for Go SDK. In the Readme file, it is mentioned that we can pass the context and apply the constraints, but context values are ignored.

**Comment by chrusty** [comment]
Hello @tank-pooja, thanks for your interest in the FeatureHub Go SDK!

Certainly, client-evaluated rollout strategies ARE supported by this SDK, and the examples should certainly work for you. I have spent quite a lot of time on this logic recently! One thing I noticed was that if I used the wrong SDK key then evaluation strategies did not work, so you need to be careful to use the correct key.

**Comment by tank-pooja** [comment]
Hey @chrusty , thanks for the quick reply.
I am using the client key as SDK Key, correct me if I am using the wrong one.
For your reference, I am sharing the screenshot
![FeatureHub](https://user-images.githubusercontent.com/62046605/135592619-6b3a63cb-e9d2-4f1d-bb76-9fe45f0693b3.png)

I have set up the "random" boolean feature flag with default off and applied percentage-based rollout.  When I access the URL through it always returns the same response `Hello, {name}`.

**Comment by chrusty** [comment]
I'll see if I can reproduce this

**Comment by chrusty** [comment]
Hi @tank-pooja, I have an update for you.

I tried to reproduce this, and actually there was an issue in the README.md file! If you want to test the random strategy then you need to hit a different URL.

I've [pushed a commit which fixes this](https://github.com/featurehub-io/featurehub-go-sdk/commit/3c991e882a7fb472c16b2ec38aa0b5d8738d04ff) documentation.

Here is a screenshot for the "mapped" endpoint. You can see that the response is always the same:
![mapped](https://user-images.githubusercontent.com/1902132/135676314-d444ea9c-8ac3-4431-9867-27e1aec9cdd9.png)

Here is a screenshot for the "random" endpoint. You can see that there is roughly a 50/50 split:
![random](https://user-images.githubusercontent.com/1902132/135676379-51ecab20-81cb-432f-a040-30648e5a8cb5.png)

I'm sorry for the confusion my documentation error has caused! Please let me know if this works for you now.

**Comment by chrusty** [comment]
Hi @tank-pooja. Hopefully you're OK with this resolution, so we'll close this issue now.

Please let us know if you have any further questions about it, and thanks for your interest in the project!
