### ISSUE TITLE
Strategy.proceedWithAttributes doesn't check userkey

### ISSUE THREAD

**Issue by iskorotkov** [featurehub-io/featurehub-go-sdk#3]
## Problem

We are trying to enable specific features for selected users based on their ID in our database. I thought it is something that must be done using userkey value, but client library doesn't check userkey value when evaluating strategies:

https://github.com/featurehub-io/featurehub-go-sdk/blob/c7c1fec97ff5c23e947dd596257bde63faa45d56/pkg/models/strategies.go#L105-L176

However admin pages allow using userkey value so it seems like it must work:

![image](https://user-images.githubusercontent.com/24717100/131457719-fba7f4bc-1003-49b2-8091-3e497cea38cb.png)

## Possible workarounds

Now it's possible to set custom value and use it in strategies. However, it isn't clear why we need userkey value if it's not used.

## Solution

Add a branch to the switch statement and check the userkey value.

## Reason

From my point of view the ability to use userkey in a strategy means that the strategy will be used for specific users just like it works with other available parameters. However, it doesn't work like expected.

**Comment by chrusty** [comment]
Hey @iskorotkov thanks for raising this! I'll chat to some of the other SDK devs about how this logic is supposed to work, and see if I can get a new version in place for you to try out.

**Comment by chrusty** [comment]
@iskorotkov OK this has been merged and hopefully does what you want. I've tagged a [new release](https://github.com/featurehub-io/featurehub-go-sdk/releases/tag/1.3.1) so please give it a go and let us know if you still have issues!
