### ISSUE TITLE
Numbers are matched only if they are float64

### ISSUE THREAD

**Issue by iskorotkov** [featurehub-io/featurehub-go-sdk#4]
## Problem

We are trying to enable certain features for specific cities/clients using their ID (type uint). If we pass IDs in custom values in context as is, we get errors in output and the result is 'false'.

## Workaround

We can cast every number that we are passing as custom values to float64 in our code. It seems ugly to me.

## Solution

I think it's possible to do something here to support more number types:

https://github.com/featurehub-io/featurehub-go-sdk/blob/c7c1fec97ff5c23e947dd596257bde63faa45d56/pkg/strategies/type_number.go#L11-L30

Maybe we can cast to float64 here and/or use `reflect` package to solve the problem.

## Reason

I expect type 'number' to work with all numbers, but I get errors when I try to use something other than float64 in custom values. I expect it to work flawlessly with other types as well without having me to cast everything to float64 in my code.

**Comment by chrusty** [comment]
Hi @iskorotkov. This all boils down to the way that numeric values are presented in JSON (which is how the SDK received data from the FeatureHub server).

We could probably make this more explicit in the SDK? Go is a strongly-typed language so at some point the number needs to be cast / asserted for safety's sake.

It may also be possible to attempt to cast things within the SDK, but of course errors may arise and will still need to be handled by the user.

**Comment by chrusty** [comment]
Hello @iskorotkov. I'm pleased to announce [a new version of the SDK](https://github.com/featurehub-io/featurehub-go-sdk/releases/tag/1.3.2) which is able to accept any numeric type for comparison (apart from float32 which I'll still need to work on).

Thank you for bringing this to our attention, and please let us know if this works / doesn't work for you!
